name: Deploy to GitHub Pages

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9

      - name: Build project
        run: dotnet build skunk-html.fsproj

      - name: Run F# code to generate HTML
        run: dotnet run --project skunk-html.fsproj

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: "./skunk-html-output"

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4